# -*- coding: utf-8 -*-
"""List&Match.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JaAs9u9vxm7IHjWDia8SGCYGZy-rG_pj
"""

#Soal no 1 Dan 2
Kendaraan=["BG1234D","Supra","150Cc","Hitam"]
Kendaraan.append ("150 juta")
Kendaraan.append ("4 roda")
Kendaraan.insert (2,"Honda")
Kendaraan.insert (3,"Mobil")


print(Kendaraan)

#Soal no 3

pesan = """Selamat datang di aplikasi menghitung
Masukkan pilihan :
1. Menghitung luas persegi panjang
2. Menghitung luas lingkaran
3. Menghitung luas segitiga
masukan angka :
 """

pilihan = input(pesan)

match pilihan :
    case "1":
         print("kamu memilih untuk menghitung luas persegi panjang")
         sisi = int(input("masukkan besar sisinya:"))
         luas_persegi= sisi*sisi
         print("luas dari persegi dengan sisinya",sisi,"adalah",luas_persegi)
    case "2":
         print("Kamu memilih menghitung luas lingkaran")
         phi = 3.14
         r = int(input("masukkan besar jari-jari lingkaran:"))
         luas_lingkaran=phi*r*r
         print("luas lingkaran dengan jari jari",r,"adalah",luas_lingkaran)
    case "3":
         print("kamu memilih menghitung luas segitiga")
         alas =int(input("masukkan besar alas:"))
         tinggi =int(input("masukkan tinggi segitiga:"))
         luas_segitiga= alas*tinggi/2
         print("luas segitiga dengan tinggi",tinggi,"& alas", alas,"adalah",luas_segitiga)
    case _:
         print("input Tidak tersedia")